// Generated by https://quicktype.io

import { GUID, Content, Links } from './common';

export interface Project {
  id: number;
  date: string;
  date_gmt: string;
  guid: GUID;
  modified: string;
  modified_gmt: string;
  slug: string;
  status: string;
  type: string;
  link: string;
  title: GUID;
  content: Content;
  excerpt: Content;
  featured_media: number;
  template: string;
  meta: any[];
  acf: ProjectCustomFields;
  _links: Links;
}

interface ProjectCustomFields {
  url: string;
}
